_BASE_: "../dota-1.5/600.yaml"

DATASETS:
  #DATA_DIR: "/home/qilei/DATASETS/trans_drone/"
  DATA_DIR: "/data2/qilei_chen/DATA/trans_drone"
  TRAIN: ("trans_drone_wide_train",)
  TEST: ("trans_drone_wide_val",)

INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  MIN_SIZE_TEST: 1024

MODEL:
  DAFNE:
    NUM_CLASSES: 3

SOLVER:
  REFERENCE_WORLD_SIZE: 2
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  WEIGHT_DECAY_BIAS: 0.0001

TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 2000

  AUG:
    ENABLED: False
    MIN_SIZES: (256, 512, 756, 1024, 1536)
    MAX_SIZE: 1536
    FLIP: True

OUTPUT_DIR: /data2/qilei_chen/DATA/trans_drone/DAFNe/1024output