_BASE_: "../dota-1.5/600.yaml"

DATASETS:
  DATA_DIR: "/home/qilei/DATASETS/trans_drone/"
  #DATA_DIR: "/data2/qilei_chen/DATA/trans_drone"
  TRAIN: ("trans_drone_train_mix",)
  TEST: ("trans_drone_test_mix",)

INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  MIN_SIZE_TEST: 1024

MODEL:
  DAFNE:
    NUM_CLASSES: 3

SOLVER:
  REFERENCE_WORLD_SIZE: 2
  IMS_PER_BATCH: 8
  BASE_LR: 0.0025
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500
  WEIGHT_DECAY_BIAS: 0.0001
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 2000
  STEPS:
  - 14000
  - 18000  

TEST:
  EVAL_PERIOD: 200
  IOU_TH: 0.1
  DETECTIONS_PER_IMAGE: 2000
  NUM_PRED_VIS: 50
  AUG:
    ENABLED: False
    MIN_SIZES: (256, 512, 756, 1024, 1536)
    MAX_SIZE: 1536
    FLIP: True

#OUTPUT_DIR: /data2/qilei_chen/DATA/trans_drone/DAFNe/1024_output
OUTPUT_DIR: /home/qilei/DATASETS/trans_drone/DAFNe/1024_mix_output